name: C++ CI/CD Pipeline

on:
  push:
    branches:
       - main
  pull_request:
    branches:
       - main
       
jobs:
  build:
     runs-on: ubuntu-latest
     
     steps:
     - name: Checkout Code
       uses: actions/checkout@v3
       
     - name: Cache APT Packages
       uses: actions/cache@v3
       with:
         path: /var/cache/apt/archives
         key: apt-${{ runner.os }}-${{ hashFiles('.github/workflows/ci-cd.yml') }}
         restore-keys: apt-${{ runner.os }}-
       
     - name: Install Dependencies
       run: sudo apt-get update && sudo apt-get install -y cmake g++ libgtest-dev
     
     - name: Configure CMake
       run: cmake -S . -B build
     
     - name: Build Project
       run: cmake --build build
       
     - name: Run Unit Tests
       run: ./build/runTests #--gtest_filter=-EvenOddTest.*
